//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekersFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANSWER()
        {
            this.ANSWERSCOREs = new HashSet<ANSWERSCORE>();
            this.APPLICANTSANSWERS = new HashSet<APPLICANTSANSWER>();
        }
    
        public int Id { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer1 { get; set; }
    
        public virtual QUESTION QUESTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWERSCORE> ANSWERSCOREs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICANTSANSWER> APPLICANTSANSWERS { get; set; }
    }
}
