//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekersFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANTSANSWER
    {
        public int Id { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
    
        public virtual ANSWER ANSWER { get; set; }
        public virtual APPLICANT APPLICANT { get; set; }
    }
}
