//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekersFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeekersDBEntities : DbContext
    {
        public SeekersDBEntities()
            : base("name=SeekersDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANSWER> ANSWERs { get; set; }
        public virtual DbSet<ANSWERSCORE> ANSWERSCOREs { get; set; }
        public virtual DbSet<APPLICANT> APPLICANTS { get; set; }
        public virtual DbSet<APPLICANTSANSWER> APPLICANTSANSWERS { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<QUESTION> QUESTIONs { get; set; }
    }
}
